// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfPay.Data;

namespace SelfPay.Migrations
{
    [DbContext(typeof(SelfPayContext))]
    [Migration("20191213162712_outrasEntidades")]
    partial class outrasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SelfPay.Models.Carrinho", b =>
                {
                    b.Property<int>("Carrinho_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Carrinho_dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Carrinho_total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Cliente_id")
                        .HasColumnType("int");

                    b.Property<int?>("Pedido_id")
                        .HasColumnType("int");

                    b.HasKey("Carrinho_id");

                    b.HasIndex("Pedido_id");

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("SelfPay.Models.CarrinhoItens", b =>
                {
                    b.Property<int>("CarrinhoItens_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarrinhoItens_carrinho_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CarrinhoItens_dataCadatro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CarrinhoItens_quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("CarrinhoItens_valorTotalItem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CarrinhoItens_valorUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Carrinho_id")
                        .HasColumnType("int");

                    b.Property<int>("Carrinhoitens_produto_id")
                        .HasColumnType("int");

                    b.HasKey("CarrinhoItens_id");

                    b.HasIndex("Carrinho_id");

                    b.ToTable("Carrinhoitens");
                });

            modelBuilder.Entity("SelfPay.Models.Categoria", b =>
                {
                    b.Property<int>("Categoria_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria_ativo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Categoria_dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Categoria_nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Categoria_id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SelfPay.Models.Cliente", b =>
                {
                    b.Property<int>("Cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Carrinho_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Cliente_id");

                    b.HasIndex("Carrinho_id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SelfPay.Models.Pedido", b =>
                {
                    b.Property<int>("Pedido_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarrinhoItens_id")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoItens_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Pedido_dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Pedido_valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Pedido_id");

                    b.HasIndex("PedidoItens_id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SelfPay.Models.PedidoItens", b =>
                {
                    b.Property<int>("PedidoItens_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CarrinhoItens_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("PedidoItens_dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PedidoItens_produto_id")
                        .HasColumnType("int");

                    b.Property<int>("PedidoItens_quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("PedidoItens_valorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PedidoItens_valorUnidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Pedidoitens_pedido_id")
                        .HasColumnType("int");

                    b.HasKey("PedidoItens_id");

                    b.HasIndex("CarrinhoItens_id");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("SelfPay.Models.Produto", b =>
                {
                    b.Property<int>("Produto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PedidoItens_id")
                        .HasColumnType("int");

                    b.Property<string>("Produto_ativo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Produto_desc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Produto_nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Produto_preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Produto_precoPromo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Produto_id");

                    b.HasIndex("PedidoItens_id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SelfPay.Models.ProdutoCategoria", b =>
                {
                    b.Property<int>("Categoria_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ProdutoCategoria_dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Produto_id")
                        .HasColumnType("int");

                    b.HasKey("Categoria_id");

                    b.ToTable("ProdutoCategoria");
                });

            modelBuilder.Entity("SelfPay.Models.Carrinho", b =>
                {
                    b.HasOne("SelfPay.Models.Pedido", "Pedido")
                        .WithMany("Carrinhos")
                        .HasForeignKey("Pedido_id");
                });

            modelBuilder.Entity("SelfPay.Models.CarrinhoItens", b =>
                {
                    b.HasOne("SelfPay.Models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("Carrinho_id");
                });

            modelBuilder.Entity("SelfPay.Models.Cliente", b =>
                {
                    b.HasOne("SelfPay.Models.Carrinho", "Carrinho")
                        .WithMany("Clientes")
                        .HasForeignKey("Carrinho_id");
                });

            modelBuilder.Entity("SelfPay.Models.Pedido", b =>
                {
                    b.HasOne("SelfPay.Models.PedidoItens", "PedidoItens")
                        .WithMany("Pedidos")
                        .HasForeignKey("PedidoItens_id");
                });

            modelBuilder.Entity("SelfPay.Models.PedidoItens", b =>
                {
                    b.HasOne("SelfPay.Models.CarrinhoItens", "CarrinhoItens")
                        .WithMany("PedidoItenss")
                        .HasForeignKey("CarrinhoItens_id");
                });

            modelBuilder.Entity("SelfPay.Models.Produto", b =>
                {
                    b.HasOne("SelfPay.Models.PedidoItens", "PedidoItens")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoItens_id");
                });
#pragma warning restore 612, 618
        }
    }
}
